name = "CClosures"
uuid = "6238cdf7-1651-426a-bbec-388a63a3d275"
authors = ["melonedo <44501064+melonedo@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
